### ISSUE TITLE
issue related multiple users

### ISSUE THREAD

**Issue by priyanka1098** [zone-eu/zone-mta#228] opened 2020-02-20 09:43 UTC
Hii all,
I am new to zone-mta .
I have installed zone-mta in ubuntu 16.04 and also configured a user for  sending mail which was perfectly working. but it works only in case of single user and not in multiple users . could you please tell me how can i configure it for multiple users.

Thanks for Help!!

**Comment by louis-lau** [comment] 2020-02-20 09:45
Not sure what you mean. If you add a second user you have multiple users right?

**Comment by priyanka1098** [comment] 2020-02-20 09:51
@louis-lau Thanks for the reply

My concern is that i have  tested sending mail to single user. it's perfectly working.

But i'm not able to add multiple users in zone-mta.

Please suggest me how can i configure multiple user & multiple credentials.
Please Help!

**Comment by louis-lau** [comment] 2020-02-20 09:53
Riiiight, sorry. I did not realize this was an issue on ZoneMTA. ZMTA is a framework, if you need authentication with multiple users you need to write a plugin. Seems like a duplicate of this issue?

https://github.com/zone-eu/zone-mta/issues/225

**Comment by priyanka1098** [comment] 2020-02-20 09:58
I am very new to ZMTA so please help me to add more than one user and its credentials.
 i have used this plugin /zone-mta-template/plugins/example-auth.js
for using user authentication . it is working only for single user. how can i configure in this file for  multiple users.
Thanks for help.

**Comment by louis-lau** [comment] 2020-02-20 10:02
It's just JavaScript, you can do whatever you want. In the addhook function call next() if you want authentication to succeed, throw an error if you want the authentication to fail. Tha logic is up to you, this logic doesn't have to do anything with ZoneMTA. It's JavaScript :)

**Comment by priyanka1098** [comment] 2020-02-20 10:08
Sorry ,  I don't  know JavaScript  or any other programming language . so could please help me with the code for adding more users & their credentials.

**Comment by andris9** [comment] 2020-02-20 10:15
If you just want a working MTA application then you should probably look at Postfix instead. ZoneMTA is meant for setups that need more custom approach than what Postfix could provide.

**Comment by manhnguyenduc** [comment] 2020-04-03 02:56
I have added an API to support auth with many users

Add user to collection users 

`db.users.insert({"username": "user", "password": "pass"})
`

Add API to lib/api-server.js 

```
this.server.get('/auth', (req, res, next) => {
            let time = new Date().toISOString();

            this.queue.mongodb
                .collection('users')
                .findOne({"username": decodeURIComponent(req.username)}, function (err, result) {
                    if (err) throw err;
                    // console.log(result);
                    if (result === null ||decodeURIComponent(req.authorization.basic.password) !== decodeURIComponent(result.password)) {
                        res.statusCode = 401;
                        res.setHeader('WWW-Authenticate', 'Basic realm="Secure Area"');
                        return res.json({
                            time,
                            error: 'Authentication required'
                        });
                    }

                    res.json({
                        user: req.username,
                        time
                    });

                });

            // the actual response does not matter as long as it's 2xx range

            next();
        });
```

@priyanka1098 : Hope it can help you

**Comment by dazoot** [comment] 2020-06-18 14:43
Can we close this ?

**Comment by dazoot** [comment] 2021-03-09 19:46
@andris9 close ?

**Closed** 2021-03-10 07:41 UTC
