### ISSUE TITLE
Unhandled error / missing check in sender.js

### ISSUE THREAD

**Issue by jkramarz** [zone-eu/zone-mta#3] opened 2016-09-12 20:53 UTC
When sending email to an unavailable host (eg. firewall is blocking outbound connection) following error occurs:
```
info Feeder RECEIVED 1572028b61b000a5f3 (From: lenwe@localhost; To: test@lenwe.net)
info Sender/default/16398 Failed to connect to aspmx2.googlemail.com[64.233.189.27] for lenwe.net from default (edziu[0.0.0.0])
buffer.js:186
    throw new TypeError('"encoding" must be a valid string encoding');
    ^

TypeError: "encoding" must be a valid string encoding
    at fromString (buffer.js:186:11)
    at Function.Buffer.from (buffer.js:94:12)
    at getConnection (/home/jkramarz/zone-mta/lib/sender.js:150:48)
    at tryConnectMX (/home/jkramarz/zone-mta/lib/sender.js:349:28)
    at tryConnectIP (/home/jkramarz/zone-mta/lib/sender.js:365:36)
    at SMTPConnection.connection.once.err (/home/jkramarz/zone-mta/lib/sender.js:419:40)
    at SMTPConnection.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at SMTPConnection.emit (events.js:188:7)
    at SMTPConnection._onError (/home/jkramarz/zone-mta/node_modules/smtp-connection/lib/smtp-connection.js:518:10)
ERR! Child/default/16398 Sender process 0c30d0ee9771b84da546 for default exited with 1
```

**Comment by andris9** [comment] 2016-09-13 10:24
This was caused by a typo (regression), fixed now. I guess it's time to invest some time into creating more unit tests to catch these kind of errors.

**Closed by andris9** 2016-09-13 10:24 UTC
